# =============================================================================
# terraform/backend.hcl — Remote Backend Configuration
# =============================================================================
# This file is generated by running terraform/bootstrap.
# After bootstrap completes, copy the output values here.
#
# HOW TO USE
# ──────────
# Each environment uses a different KEY (path in the bucket),
# but the same bucket and table.
#
#   terraform init -backend-config=../backend.hcl \
#                  -backend-config="key=qa/terraform.tfstate"
#
#   terraform init -backend-config=../backend.hcl \
#                  -backend-config="key=prod/terraform.tfstate"
#
# The GitHub Actions workflow passes these automatically.
# =============================================================================

# Filled in from bootstrap output:
bucket         = "smartapps-terraform-state-400844546140"
region         = "eu-west-1"
dynamodb_table = "smartapps-tf-locks"
encrypt        = true
